#!/bin/bash
sudo dnf update -y 
sudo dnf install wget git unzip java-17 -y
cd /opt
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-24.12.0.100206.zip
sudo unzip sonarqube-24.12.0.100206
sudo rm -rf sonarqube-24.12.0.100206.zip
sudo mv sonarqube-24.12.0.100206/ sonarqube
sudo useradd -r -d /opt/sonarqube -s /bin/false sonar
sudo chown -R sonar:sonar /opt/sonarqube
sudo chmod -R 775 /opt/sonarqube

sudo tee /etc/systemd/system/sonar.service > /dev/null <<-"EOF"
[Unit]
Description=sonarqube
After=network.target

[Service]
Type=forking
User=sonar
Group=sonar
LimitNOFILE=65536
WorkingDirectory=/opt/sonarqube
ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl start sonar
sudo systemctl enable sonar
sudo systemctl status sonar

echo "sonar is ready at http://localhost:9000"
