#!/bin/bash
sudo dnf update -y 
sudo dnf install wget git unzip java-17 -y
cd /opt
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-24.12.0.100206.zip
sudo unzip sonarqube-24.12.0.100206
sudo rm -rf sonarqube-24.12.0.100206.zip
sudo mv sonarqube-24.12.0.100206/ sonarqube
sudo useradd -r -d /opt/sonarqube -s /bin/false sonar
sudo chown -R sonar:sonar /opt/sonarqube
sudo chmod -R 775 /opt/sonarqube
sudo -u sonar /opt/sonarqube/bin/linux-x86-64/sonar.sh start
sudo -u sonar /opt/sonarqube/bin/linux-x86-64/sonar.sh status